version: "2"

checks:
  method-lines:
    enabled: false

plugins:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 70

exclude_patterns:
- static/**/*